"""
PASO 2 — Shapefile filename vs CdgActvdd validation script generator.

Generates an ArcPy script (for ArcGIS Pro Python window) that validates
whether each downloaded shapefile's internal CdgActvdd field matches the
expected activity code from Smartsheet.

Note: arcpy is NOT available in the Flask server environment.
All arcpy calls are emitted as strings inside the generated script.
"""
from __future__ import annotations

import re
import textwrap


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _is_c2_filename(stem: str) -> bool:
    """
    Heuristic: C2 filenames follow {CONTRATO}_{ORG}_{QUARTER} pattern.
    E.g. 'AR-PPD-001_ONG_Sur_T2026Q1' — contains a dash and no pure CODIGO pattern.
    C1/C3 CODIGOs look like '241014_C1_ROM_a' (starts with 6-digit date prefix).
    """
    return not bool(re.match(r'^\d{6}_C[13]_', stem))


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def script_validate_shp_codes(p: dict) -> str:
    """
    Generate an arcpy validation script for ArcGIS Pro Python window.

    Args in p:
      - shp_folder: folder to scan for .shp files (absolute path)
      - component: "C1", "C2", "C3", or "" / "All" for all components
      - ss_csv_path: optional path to Smartsheet CSV with CÓDIGO_DE_LA_ACTIVIDAD column

    Returns:
      A complete Python script string ready to paste into ArcGIS Pro.

    Logic generated:
      1. Recursively scan shp_folder for .shp files
      2. Check CdgActvdd field exists in each SHP
      3. C1/C3: filename stem must equal the unique CdgActvdd value
      4. C2: CdgActvdd set via area matching — warn if value looks like
             fallback ({CONTRATO}_{ORG}_{QT}) instead of a valid CODIGO
      5. If ss_csv_path provided: warn if CdgActvdd not in SS PK list
      6. Print [OK] OK / [!] WARNING / [X] ERROR per file
    """
    shp_folder = p.get("shp_folder", r"C:\path\to\shp_folder")
    component = p.get("component", "")  # "C1", "C2", "C3", or "" = all
    ss_csv_path = p.get("ss_csv_path", "")

    # Normalise component filter
    comp_filter = component.upper() if component and component.upper() != "ALL" else ""

    ss_csv_block = ""
    if ss_csv_path:
        ss_csv_block = textwrap.dedent(f"""\
            # Cargar PK de Smartsheet / Load Smartsheet PKs
            ss_codes = set()
            try:
                import csv as _csv
                with open(r"{ss_csv_path}", newline='', encoding='utf-8-sig') as _f:
                    for _row in _csv.DictReader(_f):
                        # Buscar columna CÓDIGO / Find CÓDIGO column
                        for _k, _v in _row.items():
                            if 'DIGO' in _k.upper() or 'CODIGO' in _k.upper():
                                if _v:
                                    ss_codes.add(_v.strip())
                                break
                print(f"  SS PKs cargados / SS PKs loaded: {{len(ss_codes)}}")
            except Exception as _e:
                print(f"  [!]  No se pudo leer SS CSV / Could not read SS CSV: {{_e}}")
        """)
    else:
        ss_csv_block = "ss_codes = set()  # No SS CSV provided\n"

    comp_filter_block = ""
    if comp_filter:
        comp_filter_block = textwrap.dedent(f"""\
            # Filtrar por componente / Filter by component
            shp_files = [s for s in shp_files if r'\\{comp_filter}\\' in s or
                         os.path.basename(os.path.dirname(s)).upper().startswith('{comp_filter}') or
                         f'_{comp_filter}_' in os.path.splitext(os.path.basename(s))[0].upper() or
                         os.path.splitext(os.path.basename(s))[0].upper().startswith('{comp_filter}')]
            print(f"Filtrado a componente {comp_filter}: {{len(shp_files)}} archivos / Filtered to {comp_filter}: {{len(shp_files)}} files")
        """)

    script = textwrap.dedent(f"""\
        # ═══════════════════════════════════════════════════════════════════════
        # PASO 2: Validación CdgActvdd vs nombre de archivo SHP
        # PASO 2: SHP filename vs CdgActvdd field validation
        # Generado por / Generated by: Flask AR Workflow Server
        # Ejecutar en / Run in: ArcGIS Pro Python window
        # ═══════════════════════════════════════════════════════════════════════
        import arcpy
        import os
        import re

        # ── Configuración / Configuration ──────────────────────────────────────
        SHP_FOLDER = r"{shp_folder}"

        # ── Cargar Smartsheet PKs (si se proporcionó CSV) ──────────────────────
        # Load Smartsheet PKs (if CSV was provided)
        {ss_csv_block}
        # ── Escanear carpeta recursivamente / Recursive folder scan ───────────
        shp_files = []
        for root, dirs, files in os.walk(SHP_FOLDER):
            for fname in files:
                if fname.lower().endswith('.shp'):
                    shp_files.append(os.path.join(root, fname))

        if not shp_files:
            print("[X]  No se encontraron archivos .shp en / No .shp files found in:", SHP_FOLDER)
        else:
            print(f"Encontrados / Found: {{len(shp_files)}} archivos .shp")

        {comp_filter_block}
        # ── Función: detectar si un valor es fallback C2 ──────────────────────
        # Function: detect whether a CdgActvdd value is a C2 fallback
        def _is_c2_fallback(val):
            \"\"\"
            Fallback C2 pattern: {{CONTRATO}}_{{ORG}}_T{{year}}Q{{n}}
            e.g. 'AR-PPD-001_ONG_Sur_T2026Q1'
            A proper CODIGO looks like '241014_C2_PPD_b' (starts with 6 digits).
            \"\"\"
            if re.match(r'^\\d{{6}}_C[123]_', val):
                return False  # Es un CODIGO válido / Is a valid CODIGO
            if re.search(r'_T\\d{{4}}Q\\d', val):
                return True   # Parece fallback / Looks like fallback
            return None  # Indeterminado / Indeterminate

        # ── Validación principal / Main validation ─────────────────────────────
        ok_count = 0
        warn_count = 0
        err_count = 0

        for shp_path in sorted(shp_files):
            stem = os.path.splitext(os.path.basename(shp_path))[0]

            # Determinar componente desde la ruta / Determine component from path
            path_upper = shp_path.upper()
            if '_C1_' in stem.upper() or r'\\C1\\' in path_upper:
                comp = 'C1'
            elif '_C2_' in stem.upper() or r'\\C2\\' in path_upper:
                comp = 'C2'
            elif '_C3_' in stem.upper() or r'\\C3\\' in path_upper:
                comp = 'C3'
            else:
                # Heurística adicional / Additional heuristic
                comp = 'C2' if re.search(r'AR-[A-Z]{{3}}-\\d{{3}}', stem) else 'C1'

            print(f"\\n  Archivo / File: {{stem}}.shp  [{{comp}}]")

            # ── Verificar campo CdgActvdd / Check CdgActvdd field ──────────────
            try:
                field_names = [f.name for f in arcpy.ListFields(shp_path)]
            except Exception as e:
                print(f"  [X]  ERROR: No se pudo leer campos / Could not read fields: {{e}}")
                err_count += 1
                continue

            if 'CdgActvdd' not in field_names:
                print(f"  [X]  ERROR: Campo CdgActvdd no existe / CdgActvdd field missing")
                err_count += 1
                continue

            # Obtener valores únicos de CdgActvdd / Get unique CdgActvdd values
            cdg_values = set()
            with arcpy.da.SearchCursor(shp_path, ['CdgActvdd']) as cur:
                for row in cur:
                    if row[0]:
                        cdg_values.add(str(row[0]).strip())

            if not cdg_values:
                print(f"  [X]  ERROR: CdgActvdd está vacío / CdgActvdd is empty")
                err_count += 1
                continue

            # ── C1 / C3 validation ─────────────────────────────────────────────
            if comp in ('C1', 'C3'):
                expected = stem
                if cdg_values == {{expected}}:
                    print(f"  [OK]  OK — CdgActvdd '{{expected}}' coincide con nombre de archivo / matches filename")
                    ok_count += 1
                else:
                    mismatch_list = ', '.join(sorted(cdg_values))
                    print(f"  [X]  ERROR — Nombre: '{{stem}}' | CdgActvdd: '{{mismatch_list}}'")
                    print(f"       El valor CdgActvdd debe coincidir exactamente con el nombre del archivo.")
                    print(f"       CdgActvdd must match the filename exactly.")
                    err_count += 1

            # ── C2 validation ──────────────────────────────────────────────────
            elif comp == 'C2':
                any_ok = False
                any_fallback = False
                any_invalid = False
                valid_codes = []
                fallback_codes = []
                invalid_codes = []

                for val in sorted(cdg_values):
                    fb = _is_c2_fallback(val)
                    if fb is False:
                        valid_codes.append(val)
                        any_ok = True
                    elif fb is True:
                        fallback_codes.append(val)
                        any_fallback = True
                    else:
                        invalid_codes.append(val)
                        any_invalid = True

                if valid_codes:
                    print(f"  [OK]  OK — CdgActvdd válido(s) / Valid CdgActvdd(s): {{', '.join(valid_codes)}}")
                    ok_count += 1
                if fallback_codes:
                    print(f"  [!]   ADVERTENCIA / WARNING — CdgActvdd parece valor fallback (no CODIGO real):")
                    print(f"       Valor(s) / Value(s): {{', '.join(fallback_codes)}}")
                    print(f"       La función shp_add_CdgActvdd_c2() usó el fallback ({{stem}}) en lugar de")
                    print(f"       un CÓDIGO de la actividad real. Verifique el SHP manualmente.")
                    print(f"       shp_add_CdgActvdd_c2() used fallback — verify SHP manually.")
                    warn_count += 1
                if invalid_codes:
                    print(f"  [!]   ADVERTENCIA / WARNING — CdgActvdd con formato no reconocido / Unrecognised format: {{', '.join(invalid_codes)}}")
                    warn_count += 1

                # Si no hubo válidos ni fallbacks, reportar error
                # If no valid or fallback codes found, report error
                if not any_ok and not any_fallback and not any_invalid:
                    print(f"  [X]  ERROR — CdgActvdd sin valores reconocibles / No recognisable CdgActvdd values")
                    err_count += 1

            # ── Verificar contra SS CSV / Check against SS CSV ─────────────────
            if ss_codes:
                for val in sorted(cdg_values):
                    if val not in ss_codes:
                        print(f"  [!]   ADVERTENCIA / WARNING — '{{val}}' no está en el CSV de Smartsheet.")
                        print(f"       '{{val}}' not found in Smartsheet CSV.")
                        warn_count += 1
                        break  # Solo reportar una vez por archivo / Report once per file

        # ── Resumen / Summary ──────────────────────────────────────────────────
        total = len(shp_files)
        print("\\n" + "═" * 60)
        print(f"RESUMEN / SUMMARY: {{total}} archivos / files")
        print(f"  [OK]  OK:            {{ok_count}}")
        print(f"  [!]   Advertencias:  {{warn_count}}")
        print(f"  [X]  Errores:        {{err_count}}")
        print("═" * 60)
        if err_count == 0 and warn_count == 0:
            print("[OK]  Validación completada sin problemas. / Validation completed with no issues.")
        elif err_count == 0:
            print("[!]   Validación con advertencias — revisar C2 fallbacks.")
            print("[!]   Validation with warnings — check C2 fallbacks.")
        else:
            print("[X]  Se encontraron errores — corregir antes de PASO 3.")
            print("[X]  Errors found — fix before proceeding to PASO 3.")
    """)

    return script
